name: CI/CD
on:
  push:
    tags:
      - prod/*
jobs:
  CICD:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-1
      BUCKET: filecoin-saturn
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_GITHUB_CI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_GITHUB_CI_AWS_SECRET_ACCESS_KEY }}
          mask-aws-account-id: ${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and Push Assets
        run: |
          npm ci --also=dev
          npm run build

          aws s3 cp dist/ s3://$BUCKET --recursive \
            --exclude "*" --include "*.js" \
            --cache-control "public, max-age=3600" --only-show-errors
